// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeryLike.Infrastructure.Data;

#nullable disable

namespace VeryLike.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContenidoAudiovisualUsuario", b =>
                {
                    b.Property<int>("ListaParaVerId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ListaParaVerId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosParaVer", (string)null);
                });

            modelBuilder.Entity("VeryLike.Domain.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContenidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<double>("Puntaje")
                        .HasColumnType("float");

                    b.Property<string>("ResenaPrivada")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ResenaPublica")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContenidoId");

                    b.HasIndex("UsuarioId", "ContenidoId")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("VeryLike.Domain.Models.ContenidoAudiovisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<double>("Calificacion")
                        .HasColumnType("float");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdExterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlataformaStreaming")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Studio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoDiscriminador")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno");

                    b.ToTable("Contenidos", (string)null);

                    b.HasDiscriminator<string>("TipoDiscriminador").HasValue("ContenidoAudiovisual");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VeryLike.Domain.Models.MensajeForo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MensajesForo");
                });

            modelBuilder.Entity("VeryLike.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Correo");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VeryLike.Domain.Models.Pelicula", b =>
                {
                    b.HasBaseType("VeryLike.Domain.Models.ContenidoAudiovisual");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Pelicula");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnioPublicacion = 1997,
                            Calificacion = 4.0,
                            Genero = "Psicológico|Animación",
                            Nombre = "Perfect Blue",
                            PlataformaStreaming = "Crunchyroll",
                            Sinopsis = "Una cantante pop convertida en actriz ve cómo su sentido de la realidad se desmorona al ser acosada por un fan obsesivo.",
                            Studio = "Madhouse",
                            Duracion = "1h 21m"
                        },
                        new
                        {
                            Id = 2,
                            AnioPublicacion = 2014,
                            Calificacion = 4.5,
                            Genero = "Drama|Biografía",
                            Nombre = "The Imitation Game",
                            PlataformaStreaming = "Netflix",
                            Sinopsis = "Alan Turing y su equipo intentan descifrar el código Enigma durante la Segunda Guerra Mundial.",
                            Studio = "Black Bear Pictures",
                            Duracion = "1h 54m"
                        });
                });

            modelBuilder.Entity("VeryLike.Domain.Models.Serie", b =>
                {
                    b.HasBaseType("VeryLike.Domain.Models.ContenidoAudiovisual");

                    b.Property<int>("Temporadas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Serie");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AnioPublicacion = 2024,
                            Calificacion = 5.0,
                            Genero = "Drama histórico",
                            Nombre = "Shōgun",
                            PlataformaStreaming = "Disney+",
                            Sinopsis = "Un señor feudal japonés y un navegante inglés cambian el rumbo del Japón del siglo XVII.",
                            Studio = "FX Productions",
                            Temporadas = 1
                        },
                        new
                        {
                            Id = 4,
                            AnioPublicacion = 2022,
                            Calificacion = 4.5,
                            Genero = "Ciencia ficción|Thriller psicológico",
                            Nombre = "Severance",
                            PlataformaStreaming = "Apple TV+",
                            Sinopsis = "Empleados que se someten a un procedimiento para separar sus recuerdos laborales de los personales.",
                            Studio = "Fifth Season",
                            Temporadas = 2
                        });
                });

            modelBuilder.Entity("ContenidoAudiovisualUsuario", b =>
                {
                    b.HasOne("VeryLike.Domain.Models.ContenidoAudiovisual", null)
                        .WithMany()
                        .HasForeignKey("ListaParaVerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeryLike.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeryLike.Domain.Models.Calificacion", b =>
                {
                    b.HasOne("VeryLike.Domain.Models.ContenidoAudiovisual", "Contenido")
                        .WithMany()
                        .HasForeignKey("ContenidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeryLike.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contenido");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
