<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b9626144-42c6-49c8-93d3-707fa399cb41</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../VeryLike.Domain/VeryLike.Domain.csproj" />
    <ProjectReference Include="../VeryLike.Infrastructure/VeryLike.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
