name: CI VeryLike

on:
  push:
    branches: [ "main", "master", "pipeline-ci" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependencias
      run: dotnet restore VeryLike.Web.csproj

    - name: Compilar solución
      run: dotnet build VeryLike.Web.csproj --no-restore --configuration Release
