name: VeryLike CI Pipeline

on:
  push:
    branches: [ "main", "pipeline-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' 

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Compilar proyecto
      run: dotnet build --no-restore

    - name: Ejecutar Pruebas Automatizadas
      run: dotnet test --no-build --verbosity normal
